<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>CMS LOGIN</title>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('admin/css/layout.css'))
        ->prependStylesheet($this->basePath('admin/vendors/pnotify/dist/pnotify.nonblock.css'))
        ->prependStylesheet($this->basePath('admin/vendors/pnotify/dist/pnotify.buttons.css'))
        ->prependStylesheet($this->basePath('admin/vendors/pnotify/dist/pnotify.css'))
        ->prependStylesheet($this->basePath('admin/build/css/custom.min.css'))
        ->prependStylesheet($this->basePath('admin/vendors/animate.css/animate.min.css'))
        ->prependStylesheet($this->basePath('admin/vendors/nprogress/nprogress.css'))
        ->prependStylesheet($this->basePath('admin/vendors/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('admin/vendors/bootstrap/dist/css/bootstrap.min.css'))
    ?>

</head>

<body class="login">
<div>
    <div class="login_wrapper">
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath('admin/js/scripts.js'))
            ->prependFile($this->basePath('admin/build/js/custom.min.js'))

            ->prependFile($this->basePath('admin/vendors/pnotify/dist/pnotify.nonblock.js'))
            ->prependFile($this->basePath('admin/vendors/pnotify/dist/pnotify.buttons.js'))
            ->prependFile($this->basePath('admin/vendors/pnotify/dist/pnotify.js'))

            ->prependFile($this->basePath('admin/vendors/validator/validator-lang.js'))
            ->prependFile($this->basePath('admin/vendors/validator/validator.js'))

            ->prependFile($this->basePath('admin/vendors/nprogress/nprogress.js'))
            ->prependFile($this->basePath('admin/vendors/fastclick/lib/fastclick.js'))
            ->prependFile($this->basePath('admin/vendors/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('admin/vendors/jquery/dist/jquery.min.js'))
        ; ?>

        <?php echo $this->content;?>
    </div>
</div>
</body>
</html>
