<div class="item form-group">
    <?php echo $this->formLabel($form->get('menu_name')); ?>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php echo $this->formElement($form->get('menu_name')); ?>
        <?php echo $this->formElementErrors($form->get('menu_name'), array('class' => 'error-message')); ?>
    </div>
</div>

<div class="item form-group">
    <?php echo $this->formLabel($form->get('menu_parent')); ?>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php echo $this->formElement($form->get('menu_parent')); ?>
        <?php echo $this->formElementErrors($form->get('menu_parent'), array('class' => 'error-message')); ?>
    </div>
</div>

<div class="item form-group">
    <?php echo $this->formLabel($form->get('menu_url')); ?>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php echo $this->formElement($form->get('menu_url')); ?>
        <?php echo $this->formElementErrors($form->get('menu_url'), array('class' => 'error-message')); ?>
    </div>
</div>

<div class="item form-group">
    <?php echo $this->formLabel($form->get('menu_status')); ?>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php echo $this->formElement($form->get('menu_status')); ?>
        <?php echo $this->formElementErrors($form->get('menu_status'), array('class' => 'error-message')); ?>
    </div>
</div>
