<?php
$columnName = [
    'Menu',
    'Url',
    'Trạng thái',
];

foreach ($data['records'] as $record) {
    $columnData[$record['menu_id']] = [
        '<a href="' . $this->url('admin/default', array('controller' => $module, 'action' => 'edit'), array('query' => array('id' => $record['menu_id']))) . '">' . str_repeat('__', $record['menu_level']) . ' <strong>' . $record['menu_name'] . '</strong>' . '</a>',
        $this->escapeHtml($record['menu_url']),
        $data['status'][$record['menu_status']],
    ];
}
?>

<table class="table table-striped jambo_table bulk_action">
    <?php echo $this->partial('admin/partial/table_column_name', ['columnName' => $columnName]); ?>
    <?php echo $this->partial('admin/partial/table_column_data', ['columnData' => $columnData, 'module' => $module]); ?>
</table>
