<div class="col-sm-8" style="border-right: 1px solid #DDD">
    <?php echo $this->formViewElement()->input2($form->get('post_title'));?>
    <?php echo $this->formViewElement()->textarea($form->get('post_body')); ?>
</div>

<div class="col-sm-4">
    <?php echo $this->formViewElement()->input($form->get('post_tag'));?>
    <?php echo $this->formViewElement()->input($form->get('post_status'));?>
</div>