<?php echo $this->partial('admin/partial/form_title', ['moduleName' => $moduleName]); ?>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

            <?php echo $this->partial('admin/partial/form_action_title', ['actionName' => $actionName]); ?>

            <div class="x_content">

                <?php echo $this->message([
                    'msgError'      => $msgError,
                    'msgInfo'       => $msgInfo,
                    'msgInfoLine'   => $msgInfoLine,
                    'msgErrorLine'  => $msgErrorLine,
                ]);?>

                <br/>

                <?php
                $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-label-left', 'id' => 'frm', 'novalidate' => '']);
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <?php echo $this->partial($viewName, ['form' => $form, 'module' => $module, 'record' => $data['record'], 'data' => $data]); ?>
                <div class="ln_solid clear"></div>
                <?php echo $this->partial('admin/partial/form_button', ['form' => $form, 'module' => $module]); ?>
                <?php echo $this->form()->closeTag(); ?>

            </div>
        </div>
    </div>
</div>


