<script>
    $(document).ready(function(){

        <?php if ($msgError && $msgError != ''){?>
        var notify = new PNotify({
            title: "Lỗi",
            type: "error",
            text: "<?php echo $msgError;?>",
            styling: "bootstrap3",
        })
        <?php }?>


        <?php if ($msgInfo && $msgInfo != ''){?>
        var notify = new PNotify({
            title: "Thông báo",
            type: "info",
            text: "<?php echo $msgInfo;?>",
            styling: "bootstrap3",
        })
        <?php }?>
    })
</script>


<?php if ($msgErrorLine && $msgErrorLine != '') { ?>
    <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Có lỗi:</span>
    <?php echo $msgErrorLine; ?>
    </div><?php } ?>

<?php if ($msgInfoLine && $msgInfoLine != '') { ?>
    <div class="alert alert-info" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Thông báo:</span>
    <?php echo $msgInfoLine; ?>
    </div><?php } ?>


<button type="button" id="btn_message_modal" class="btn btn-primary" data-toggle="modal" data-target=".message-modal" style="display: none"></button>
<div class="modal fade message-modal" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel2">Thông báo</h4>
            </div>
            <div class="modal-body" id="message_body_modal"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Đóng</button>
            </div>

        </div>
    </div>
</div>

<button type="button" id="btn_message_confirm_modal" class="btn btn-primary" data-toggle="modal" data-target=".message-confirm-modal" style="display: none"></button>
<div class="modal fade message-confirm-modal" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel2">Thông báo</h4>
            </div>
            <div class="modal-body" id="message_confirm_body_modal"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id="btn_message_confirm_modal_action">Thực hiện</button>
            </div>

        </div>
    </div>
</div>