<form name="" id="frm_table" action="<?php echo $this->url('admin/default', ['controller' => $module]); ?>"
      method="post">
    <div class="x_panel">
        <?php echo $this->partial('admin/partial/table_title', ['moduleName' => $moduleName, 'module' => $module]); ?>

        <div class="x_content">
            <?php echo $this->message([
                'msgError' => $msgError,
                'msgInfo' => $msgInfo,
                'msgInfoLine' => $msgInfoLine,
                'msgErrorLine' => $msgErrorLine,
            ]); ?>

            <div class="table-responsive">
                <?php echo $this->partial($viewName, ['data' => $data, 'module' => $module]); ?>
            </div>
        </div>
        <div class="row">
            <?php echo $this->partial('admin/partial/table_count_table', ['data' => $data]); ?>
            <?php echo $this->partial('admin/partial/table_paginator2', ['data' => $data, 'module' => $module]); ?>
        </div>
    </div>
</form>
