<form name="" id="frm_table" action="<?php echo $this->url('admin/default', ['controller' => $module]); ?>"
      method="post">
    <div class="x_panel">
        <?php echo $this->partial('admin/partial/table_title', ['moduleName' => $moduleName, 'module' => $module]); ?>

        <div class="x_content">
            <?php echo $this->partial('admin/partial/message', array('msgError' => $msgError, 'msgInfo' => $msgInfo)); ?>
            <?php echo $this->partial('admin/partial/message_line', array('msgInfoLine' => $msgInfoLine, 'msgErrorLine' => $msgErrorLine)); ?>

            <div class="table-responsive">
                <?php echo $this->partial($viewName, ['data' => $data, 'module' => $module]); ?>
            </div>

        </div>
    </div>
</form>
