<?php
$columnName = [
    'ID',
    'Hình',
    'Tiêu đề',
    'Danh mục',
    'Loại',
    'Lượt xem',
    'Ngày cập nhật',
    'Trạng thái',
];

foreach ($data['data'] as $record) {

    $picture = ($record['post_picture'] == '')
        ? '<img class="img-rounded post-img" src="' . $this->basePath('admin/images/no-picture-person.png') . '" />'
        : '<img class="img-rounded post-img" src="' . $this->serverUrl() . '/thumbs/timthumb.php?src=' . $this->basePath('public/pictures/posts/' . $record['post_picture']) .'&w=25px&h=25px">';

    $postCategoryId     = $record['post_category_id'];
    $postCategoryIdStr  = '';

    foreach($postCategoryId as $k => $v) {
        $postCategoryIdStr .= $v['post_category_name'] . ',';
    }

    $columnData[$record['post_id']] = [
        $record['post_id'],
        $picture,
        '<a href="' . $this->url('admin/default', array('controller' => $module, 'action' => 'edit'), array('query' => array('id' => $record['post_id']))) . '">' . ' <strong>' . $this->escapeHtml($record['post_title']) . '</strong>' . '</a>',
        $record['post_category_names'],
        $data['postType'][$record['post_type']],
        $record['post_view'],
        $this->date()->dateTimeFormat($record['post_date_updated']),
        $data['status'][$record['post_status']],
    ];
}
?>
<?php echo $this->partial('admin/post/search_form', ['data' => $data]); ?>
<table class="table table-striped jambo_table bulk_action">
    <?php echo $this->partial('admin/partial/table_column_name', ['columnName' => $columnName]); ?>
    <?php echo $this->partial('admin/partial/table_column_data', ['columnData' => $columnData, 'module' => $module]); ?>
</table>
