<?php
echo $this->formViewElement()->input($form->get('website_email_system_name'));
echo $this->formViewElement()->input($form->get('website_email_system_host'));
echo $this->formViewElement()->input($form->get('website_email_system_port'));
echo $this->formViewElement()->input($form->get('website_email_system_ssl'));
echo $this->formViewElement()->input($form->get('website_email_system_username'));
echo $this->formViewElement()->input($form->get('website_email_system_password'));
echo $this->formViewElement()->input($form->get('website_email_from'));
echo $this->formViewElement()->input($form->get('website_email_from_name'));
echo $this->formViewElement()->input($form->get('website_email_primary_email'));
?>