<div class="animate form login_form">
    <section class="login_content">

        <h1>Mật khẩu mới</h1>

        <?php echo $this->partial('admin/partial/message', array('msgError' =>  $msgError, 'msgInfo' => $msgInfo)); ?>
        <?php echo $this->partial('admin/partial/message_line', array('msgErrorLine' =>  $msgErrorLine, 'msgInfoLine' => $msgInfoLine)); ?>

        <?php if ($msgErrorLine == '' && $msgInfoLine == ''){?>
        <?php
        $form->setAttribute('novalidate', '');
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="item form-group">
            <?php echo $this->formElement($form->get('users_password')); ?>
            <?php echo $this->formElementerrors($form->get('users_password'), ['class' => 'error-message']); ?>
        </div>

        <div class="item form-group">
            <?php echo $this->formElement($form->get('users_password_confirm')); ?>
            <?php echo $this->formElementerrors($form->get('users_password_confirm'), ['class' => 'error-message']); ?>
        </div>

        <div>
            <?php echo $this->formSubmit($form->get('users_submit')); ?>
            <?php echo $this->formHidden($form->get('csrf')); ?>
        </div>
        <div class="clearfix"></div>
        <?php echo $this->form()->closeTag(); ?>
        <?php } else {?>
        <div>
            <a class="reset_pass" href="<?php echo $this->url('admin/default', array('controller' => 'login', 'action' => 'index'));?>">Đăng nhập</a>
        </div>
        <?php }?>
    </section>
</div>



